linters:
  fast: true
  enable:
    - gci
    - wsl
    - wrapcheck
  presets:
    - bugs
    - unused
    - format
  disable:
    - scopelint

linters-settings:
  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true
run:
  timeout: 3m
modules-download-mode: readonly