apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: redis
  name: redis
spec:
  ports:
    - port: $(REDIS_PORT)
      protocol: TCP
      targetPort: redis
  selector:
    app.kubernetes.io/name: redis
