name: goreleaser

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Install Open API Generator
        run: go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@v1.11.0

      - name: Install Mock Generator
        run: go install github.com/golang/mock/mockgen@v1.6.0

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v2.7.0
        with:
          cosign-release: 'v1.12.1'

      - uses: goreleaser/goreleaser-action@v2
        name: "{{ github.event_name == 'pull_request' && 'Snapshot' }} || 'Release'"
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist {{ github.event_name == 'pull_request' && '--snapshot' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_PRIVATE_KEY: ${{secrets.COSIGN_PRIVATE_KEY}}
          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}