name: goreleaser

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write
  issues: write
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v2.7.0
        with:
          cosign-release: 'v1.12.1'

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@21f251affc0769ccac8a1cf17e937592fb492337
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: docker context create builders

      # Setup Builder
      # https://github.com/ docker/setup-buildx-action
      - name: Setup Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@f385c9ed953addec511152eb20a6021fe3d09fe6
        with:
          endpoint: builders

      - uses: goreleaser/goreleaser-action@v2
        name: ${{ (github.event_name == 'pull_request' && 'Snapshot') || 'Release' }}
        with:
          distribution: goreleaser
          version: latest
          args: release
        env:
          BUILDER: ${{ steps.buildx.outputs.name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_PRIVATE_KEY: ${{secrets.COSIGN_PRIVATE_KEY}}
          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}
      - name: Store Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: dist/artifacts.json
      - name: Store Metadata
        uses: actions/upload-artifact@v3
        with:
          name: metadata
          path: dist/metadata.json