name: goreleaser

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Install Open API Generator
        run: go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@v1.11.0

      - name: Install Mock Generator
        run: go install github.com/golang/mock/mockgen@v1.6.0
        
      - uses: goreleaser/goreleaser-action@v2
        name: Release
        if: github.event_name != 'pull_request'
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: goreleaser/goreleaser-action@v2
        name: Snapshot
        if: github.event_name == 'pull_request'
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}