name: Tests

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]
jobs:
  go-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.19', '1.18' ]
    name: Go ${{ matrix.go }} Tests
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          cache: true
      - name: Unit tests
        run: go test ./...